/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_farsystem_mqttsngatek_mqttclient_NativeMQTTClient */

#ifndef _Included_net_farsystem_mqttsngatek_mqttclient_NativeMQTTClient
#define _Included_net_farsystem_mqttsngatek_mqttclient_NativeMQTTClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_farsystem_mqttsngatek_mqttclient_NativeMQTTClient
 * Method:    connect
 * Signature: (Ljava/util/function/Consumer;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_net_farsystem_mqttsngatek_mqttclient_NativeMQTTClient_connect
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
