/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_farsystem_mqttsngatek_mqttclient_NativeMQTTClientFactory */

#ifndef _Included_net_farsystem_mqttsngatek_mqttclient_NativeMQTTClientFactory
#define _Included_net_farsystem_mqttsngatek_mqttclient_NativeMQTTClientFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_farsystem_mqttsngatek_mqttclient_NativeMQTTClientFactory
 * Method:    getClient
 * Signature: ()Lnet/farsystem/mqttsngatek/mqttclient/MQTTClient;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttclient_NativeMQTTClientFactory_getClient
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
