/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient */

#ifndef _Included_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
#define _Included_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeConnect
 * Signature: (Ljava/lang/String;IZZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeConnect
  (JNIEnv *, jobject, jstring, jint, jboolean, jboolean);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializePublishNormal
 * Signature: (ZIZII[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializePublishNormal
  (JNIEnv *, jobject, jboolean, jint, jboolean, jint, jint, jbyteArray);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeSubscribeNormal
 * Signature: (ZIILjava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeSubscribeNormal
  (JNIEnv *, jobject, jboolean, jint, jint, jstring);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeSubscribeShortName
 * Signature: (ZIILjava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeSubscribeShortName
  (JNIEnv *, jobject, jboolean, jint, jint, jstring);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeSubscribePredefined
 * Signature: (ZIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeSubscribePredefined
  (JNIEnv *, jobject, jboolean, jint, jint, jint);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeRegister
 * Signature: (ILjava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeRegister
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeSearchGW
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeSearchGW
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializeRegAck
 * Signature: (III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializeRegAck
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    serializePingReq
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_serializePingReq
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializePingResp
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNPingResp;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializePingResp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializeGwInfo
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNGwInfo;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializeGwInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializeConnAck
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNConnAck;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializeConnAck
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializePubAck
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNPubAck;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializePubAck
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializeRegAck
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNRegAck;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializeRegAck
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializeSubAck
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNSubAck;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializeSubAck
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient
 * Method:    deserializePublish
 * Signature: (Ljava/nio/ByteBuffer;)Lnet/farsystem/mqttsngatek/mqttsnclient/MQTTSNPublish;
 */
JNIEXPORT jobject JNICALL Java_net_farsystem_mqttsngatek_mqttsnclient_NativeMQTTSNClient_deserializePublish
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
